name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build Angular Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install global Angular CLI
        run: npm install -g @angular/cli @angular/compiler-cli typescript

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Verify build result
        if: failure()
        run: |
          echo "Build failed. Please fix the errors."
          exit 1
